### ISSUE TITLE
1-month roadmap

### ISSUE THREAD

**Issue by stevenphaedonos** [moocunsw/ontask2_UNSW#40]
**Currently implemented**
- Import datasource from a remote database, file upload (excel, csv) or from file hosted in an S3 bucket
- Schedule updates for datasources (remote database or S3 file)
- Flexibly join datasources together to create a DataLab without needing SQL knowledge
- Customisable web forms with permissioning for inputting data into DataLabs (e.g. attendance, grades, etc)
- Visual, rich content editor for creating conditional content based on DataLab data (i.e. mail merge)
- Send emails to students once-off or on a schedule using DataLab data and conditional content template
- Email tracking and support for collecting student feedback

**1-month roadmap**

- [x] Access feedback and tracking data from DataLab for all associated actions
- [x] Derived columns in DataLab (a column which derives its value from other columns in the DataLab - e.g. average attendance)
- [x] Expand query builder used to create conditions in conditional content - implement support for lists, ranges, etc and support querying against web form fields and feedback/tracking data
- [ ] Asynchronous email sending with rate limiting
